PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "schema_migrations" ("version" varchar(255) NOT NULL);
INSERT INTO "schema_migrations" VALUES('20140816025629');
INSERT INTO "schema_migrations" VALUES('20141009025842');
CREATE TABLE "bars" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(255), "body" text, "authors" varchar(255), "entry_url" varchar(255), "description" text, "published_at" datetime, "created_at" datetime, "updated_at" datetime);
INSERT INTO "bars" VALUES(1,'Joaquin “Waah” Dean Talks The Rise Of Ruff Ryders On ‘The Combat Jack Show’','<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2013/12/combat-jack-show-lead-alt.jpg"><img src="http://okp-cdn.okayplayer.com/wp-content/uploads/2013/12/combat-jack-show-lead-alt.jpg" alt="combat-jack-show-lead-alt" width="640" height="640" class="alignnone size-full wp-image-68136" /></a></p>
<p><strong><a href="http://www.ruffryders.com/" target="_blank">Ruff Ryders Entertainment</a></strong> co-founder <strong><a href="http://www.forbes.com/sites/zackomalleygreenburg/2010/10/06/swizz-beatz-uncle-relaunching-ruff-ryders-with-unorthodox-business-plan-dmx-to-return-jadakiss-alicia-keys-eve/" target="_blank">Joaquin &#8220;Waah&#8221; Dean</a></strong> takes the hot seat in the latest episode of <em><a href="http://www.okayplayer.com/news/big-krit-combat-jack-show-cadillactica-interview-mp3.html">The Combat Jack Show</a></em> to drop a bit of hip-hop history, beginning with his early days in the Bronx living in the apartment above <strong><a href="http://djkoolherc.com/" target="_blank">Kool Herc</a></strong> to teaming with his brother <strong><a href="http://en.wikipedia.org/wiki/Ruff_Ryders_Entertainment" target="_blank">Darrin &#8220;Dee&#8221; Dean</a></strong> to shake the flossed-out foundations of late-90&#8217;s hip-hop with the unmistakably rugged Ruff Ryders sound led by a breakout artist named <strong><a href="https://www.youtube.com/watch?v=4FFK5Oh10os" target="_blank">DMX</a></strong>.  <strong><a href="http://www.okayplayer.com/news/common-big-sean-diamonds-combat-jack-show-mp3.html">Combat Jack</a></strong> primes your ears for the latest with a brief rundown of the label&#8217;s impressive resume:</p>
<blockquote><p>You think you know the scope of the Ruff Ryders history? You heard all the stories about DMX, Eve, &#8220;The L.O.X.&#8221; Swizz Beats and the Def Jam takeover? Co-founder Joaquin &#8220;Waah&#8221; Dean takes the history back to the ground zero of Hip Hop with Kool Herc, to the legendary DMX vs Jay Z battle, to taking over the history and more. No shiny suits will be worn during the listening of this episode. Nothing but #BlockWork here b.</p></blockquote>
<p>Check the track below to listen to the full interview with Joaquin &#8220;Waah&#8221; Dean.  Stay tuned for more from <em>The Combat Jack Show</em>.</p>
<p><iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/176408937&amp;color=ff4200&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/joaquin-waah-dean-combat-jack-show-interview-mp3.html">Joaquin &#8220;Waah&#8221; Dean Talks The Rise Of Ruff Ryders On &#8216;The Combat Jack Show&#8217;</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','karaslamb','http://www.okayplayer.com/news/joaquin-waah-dean-combat-jack-show-interview-mp3.html','<p>Ruff Ryders Entertainment co-founder Joaquin &#8220;Waah&#8221; Dean takes the hot seat in the latest episode of The Combat Jack Show to drop a bit of <a class="moretag" href="http://www.okayplayer.com/news/joaquin-waah-dean-combat-jack-show-interview-mp3.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/joaquin-waah-dean-combat-jack-show-interview-mp3.html">Joaquin &#8220;Waah&#8221; Dean Talks The Rise Of Ruff Ryders On &#8216;The Combat Jack Show&#8217;</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 22:26:30.000000','2014-11-12 02:11:21.381372','2014-11-12 02:11:21.381372');
INSERT INTO "bars" VALUES(2,'OKP Premiere : Hiatus Kaiyote Tease Lush New Sounds w/ ‘By Fire’ EP Sampler + Announce ‘Choose Your Weapon’ LP','<p>&nbsp;</p>
<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/hiatus-kaiyote-by-fire-ep-sampler-mp3-miN.jpg"><img class="alignnone size-full wp-image-81117" src="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/hiatus-kaiyote-by-fire-ep-sampler-mp3-miN.jpg" alt="OKP Premiere : Hiatus Kaiyote Tease Lush New Sounds w/ ''By Fire'' EP Sampler + Announce ''Choose Your Weapon'' LP" width="715" height="715" /></a></p>
<p>The days have been dark without the organic stylings of Australia&#8217;s pioneering four-piece <a href="http://www.okayplayer.com/tag/hiatus-kaiyote%20"><strong>Hiatus Kaiyote</strong></a>. But the sun&#8217;s coming out today folks, as we have the distinct pleasure of introducing the world to a fresh new batch of sonics from one of our favorite troupes of innovators holding down the left-field with the premiere of the three-track sampler to their upcoming <em>By Fire </em>EP. Off the bat, there&#8217;s a more focused feel to the funk. &#8220;By Fire&#8221; boasts tightly knit melodies over bubblegum bass licks and electronic inflections, recalling BRAINFEEDER&#8217;s robust jazz-touched titans <a href="http://www.okayplayer.com/tag/thundercat"><strong>Thundercat</strong></a> and<strong><a href="http://www.okayplayer.comt/tag/flying-lotus"> Flying Lotus</a>. </strong></p>
<p>Gears shift towards the dirt in the next segment, taking us into the rootsy r&amp;b realm of &#8220;Laputa,&#8221; before stepping into the heavens with the soaring, staggered shuffle of &#8220;Molasses.&#8221; Finally, the lights dim to reveal a taste of their forthcoming full length treatment <i>Choose Your Weapon </i>(due out March 31st of 2015) with the 8-bit brilliance of &#8220;Atari.&#8221;</p>
<p>Ever since the drop of their dynamic and overwhelmingly impressive introductory LP <em>Tawk</em> Tomahawk, we&#8217;ve been itching for some more frequencies from the group. So if&#8217; you&#8217;ve been getting antsy, trust we can relate, but it appears the wait is just about over, as the long-awaited new chapter in the Kaiyote saga will be hitting digital and physical shelves on December 2nd. So be sure to keep it locked for the preorder links and while you&#8217;re waiting for the new joint, hold yourself over with the stunning three-song sampler of the <em>By Fire </em>EP down below. Aussie fam can catch the group&#8217;s drummer and producer <a href="http://www.okayplayer.com/tag/clever-austin"><strong>Clever Austin</strong></a> for a <a href="http://themusic.com.au/news/all/2014/11/11/hiatus-kaiyote-to-curate-and-play-new-boiler-room-tv-series/" target="_blank">Boiler Room set this Saturda</a>y.</p>
<p><iframe src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/176233892&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%" height="166" frameborder="no" scrolling="no"></iframe></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/hiatus-kaiyote-by-fire-ep-sampler-mp3.html">OKP Premiere : Hiatus Kaiyote Tease Lush New Sounds w/ &#8216;By Fire&#8217; EP Sampler + Announce &#8216;Choose Your Weapon&#8217; LP</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','zo','http://www.okayplayer.com/news/hiatus-kaiyote-by-fire-ep-sampler-mp3.html','<p>&#160; The days have been dark without the organic stylings of Australia&#8217;s pioneering four-piece Hiatus Kaiyote. But the sun&#8217;s coming out today folks, as we <a class="moretag" href="http://www.okayplayer.com/news/hiatus-kaiyote-by-fire-ep-sampler-mp3.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/hiatus-kaiyote-by-fire-ep-sampler-mp3.html">OKP Premiere : Hiatus Kaiyote Tease Lush New Sounds w/ &#8216;By Fire&#8217; EP Sampler + Announce &#8216;Choose Your Weapon&#8217; LP</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 22:00:35.000000','2014-11-12 02:11:21.426259','2014-11-12 02:11:21.426259');
INSERT INTO "bars" VALUES(3,'Common – “This War We Fight” [Official Video]','<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/common-this-war-we-fight-video-lead.jpg"><img src="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/common-this-war-we-fight-video-lead.jpg" alt="Common Drops The Official Video For &quot;This War We Fight&quot; - A Poem Penned For The Veterans Day Celebration At The White House." width="715" height="302" class="alignnone size-full wp-image-81112" /></a></p>
<p><strong><a href="http://www.okayplayer.com/news/common-rewind-that-the-light-live-queen-latifah-show-video.html">Common</a></strong> pays tribute to the fallen and all those left standing with the official video for <a href="https://www.youtube.com/watch?v=wU6Pb8ZVNLY" target="_blank">&#8220;This War We Fight&#8221;</a> &#8211; a poem written for this year&#8217;s <a href="http://www.whitehouse.gov/blog/2014/11/08/weekly-address-veterans-day-lets-honor-our-veterans" target="_blank">Veterans Day</a> celebration at the <a href="http://www.whitehouse.gov/the-press-office/2014/11/07/presidential-proclamation-veterans-day-2014" target="_blank">White House</a>.  The somber black &#038; white clip directed by <strong>Sean Glover</strong> is a mash of light and shadow scored by the <strong><a href="https://www.youtube.com/watch?v=J5tkUviUVu4" target="_blank">Puddle Of Infinity</a></strong> track <a href="https://www.youtube.com/watch?v=FCinRRg8eM8" target="_blank">&#8220;Opening Sea Morning.&#8221;</a>  Common stares out into the daylight from the confines of a dark room, where he delivers his &#8220;salute to those in fatigues and boots&#8221; and the families of those troops.  Check the footage below to watch the video for &#8220;This War We Fight.&#8221;  Purchase the <em><a href="https://itunes.apple.com/us/album/nobodys-smiling-deluxe-version/id891974297" target="_blank">Nobody&#8217;s Smiling</a></em> LP via <a href="https://itunes.apple.com/us/album/nobodys-smiling-deluxe-version/id891974297" target="_blank">iTunes</a>.  Stay tuned for more from Common.</p>
<p><iframe width="715" height="402" src="http://www.okayplayer.com//www.youtube.com/embed/wU6Pb8ZVNLY?rel=0" frameborder="0" allowfullscreen></iframe></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/common-this-war-we-fight-official-video.html">Common &#8211; &#8220;This War We Fight&#8221; [Official Video]</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','karaslamb','http://www.okayplayer.com/news/common-this-war-we-fight-official-video.html','<p>Common pays tribute to the fallen and all those left standing with the official video for &#8220;This War We Fight&#8221; &#8211; a poem written for <a class="moretag" href="http://www.okayplayer.com/news/common-this-war-we-fight-official-video.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/common-this-war-we-fight-official-video.html">Common &#8211; &#8220;This War We Fight&#8221; [Official Video]</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 20:47:08.000000','2014-11-12 02:11:21.453622','2014-11-12 02:11:21.453622');
INSERT INTO "bars" VALUES(4,'Eminem, Danny Brown & More Rep Motor City w/ “Detroit vs. Everybody”','<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/eminem-shadyxv-detroit-vs-everybody-lead.jpg"><img src="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/eminem-shadyxv-detroit-vs-everybody-lead.jpg" alt="Eminem Continues To Hit Hard Ahead Of The Release Of The Forthcoming &#039;SHADYXV&#039; LP With The Motor City Posse Cut &quot;Detroit Vs. Everybody&quot; Featuring Danny Brown, Dej Loaf, Big Sean &amp; More." width="715" height="400" class="alignnone size-full wp-image-81107" /></a></p>
<p><strong><a href="http://www.okayplayer.com/news/busta-rhymes-eminem-calm-down-single-mp3.html">Eminem</a></strong> rallies the troops to represent for the Motor City on the new single <a href="https://www.youtube.com/watch?v=vjUgJ6Cw5PU" target="_blank">&#8220;Detroit vs. Everybody,&#8221;</a> which arrives ahead of the November 24th release of the <em><a href="https://itunes.apple.com/us/album/shadyxv/id935860107" target="_blank">SHADYXV</a></em> 15-year anniversary LP from <a href="http://shadyrecords.com/" target="_blank">Shady Records</a>.  The posse cut is the latest from Eminem following the recent footage featuring <strong><a href="http://www.okayplayer.com/news/eminem-big-tigger-interview-slaughterhouse-backroom-freestyle-video.html">Slaughterhouse</a></strong> and <strong><a href="http://www.okayplayer.com/news/okayplayer-tv-yelawolf-live-at-the-roots-picnic-2011.html">Yelawolf</a></strong> for the <em><a href="http://www.okayplayer.com/news/eminem-yelawolf-slaughterhouse-shady-cxvpher-video.html">SHADY CXVPHER</a></em> series presented by <a href="http://www.vevo.com/watch/eminem/Detroit-Vs-Everybody-Audio/USUV71402761" target="_blank">VEVO</a>.  Like the clip before it, &#8220;Detroit vs. Everybody&#8221; finds an impressive collection of MC&#8217;s getting busy on the hometown anthem.  <strong>Danny Brown</strong>, <strong>Dej Loaf</strong>, <strong>Big Sean</strong>, <strong>Trick Trick</strong> and <strong>Royce Da 5&#8217;9</strong> squad up on this one to do what they do best: drop bars.  Check out the clip below to stream &#8220;Detroit vs. Everybody.&#8221;  Pre-order the <em>SHADY XV</em> LP via <a href="https://itunes.apple.com/us/album/shadyxv/id935860107" target="_blank">iTunes</a>.  Stay tuned for more from Shady Records.</p>
<p><iframe width="715" height="402" src="http://cache.vevo.com/assets/html/embed.html?video=USUV71402761&#038;autoplay=0" frameborder="0" allowfullscreen></iframe></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/eminem-detroit-vs-everybody-shady-cxvpher-video.html">Eminem, Danny Brown &#038; More Rep Motor City w/ &#8220;Detroit vs. Everybody&#8221;</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','karaslamb','http://www.okayplayer.com/news/eminem-detroit-vs-everybody-shady-cxvpher-video.html','<p>Eminem rallies the troops to represent for the Motor City on the new single &#8220;Detroit vs. Everybody,&#8221; which arrives ahead of the November 24th release <a class="moretag" href="http://www.okayplayer.com/news/eminem-detroit-vs-everybody-shady-cxvpher-video.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/eminem-detroit-vs-everybody-shady-cxvpher-video.html">Eminem, Danny Brown &#038; More Rep Motor City w/ &#8220;Detroit vs. Everybody&#8221;</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 19:13:59.000000','2014-11-12 02:11:21.481475','2014-11-12 02:11:21.481475');
INSERT INTO "bars" VALUES(5,'DJ Premier & Royce Da 5’9″ Unleash The Fierce Title-Track Of Their Forthcoming ‘PRhyme’ LP','<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/royce-da-59-dj-premier-prhyme.jpeg"><img class="alignnone size-full wp-image-81088" src="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/royce-da-59-dj-premier-prhyme.jpeg" alt="DJ Premier &amp; Royce Da 5''9&quot; Unleash The Title-Track Of Their Forthcoming ''PRhyme'' LP " width="715" height="715" /></a></p>
<p><a href="http://www.okayplayer.com/tag/dj-premier"><strong> DJ Premier</strong> </a>and <a href="http://www.okayplayer.com/tag/royce-da-59"><strong>Royce Da 5&#8217;9&#8243;</strong></a> have been teasing us with morsels from their upcoming collaborative <em>project PRhyme </em>for a minute now. Today they&#8217;ve unveiled a fierce new offering from the album with its title-track, helmed by the supreme beat constructing wizardry of <a href="http://www.okayplayer.com/tag/adrian-younge"><strong>Adrian Younge</strong></a>. &#8220;PRhyme&#8221; finds the Slaughterhouse MC going schizo, playing (at least) two sides of a dastardly dialogue, making a damn good case for him being in his prime. It&#8217;s the third drop from what is shaping up to be one of the most anticipated records of the year with the soul-selector Younge at its core, which was made even more clear in the clip for <a href="http://www.okayplayer.com/news/dj-premier-royce-da-5-9-prhyme-u-looz-video.html">&#8220;U Looz,&#8221;</a> with the fellas posting up in AY&#8217;s record shop to deliver that true-school heat. If you&#8217;ve yet to experience the dopeness of this project, I encourage you to jump back and get familiar. And if you have had the sense to put your ears to what Preemo and Royce have been cooking up, then go ahead and preorder the record on <a href="http://bit.ly/1tfZVro" target="_blank">iTunes</a> today ahead of its December 9th release. Stream the title-track to the forthcoming collaborative LP from Royce Da 5&#8217;9&#8243; and DJ Premier below and keep it locked for all things <em>PRhyme.</em></p>
<p><iframe style="width: 100%; height: 50px;" src="http://emd.sharebeast.com/embed.php?type=sharebeast&amp;file=n5hyghqio8p9&amp;dur=234.1&amp;width=100%" width="300" height="150" frameborder="0" scrolling="no"></iframe></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/dj-premier-royce-da-59-adrian-younge-prhyme-mp3.html">DJ Premier &#038; Royce Da 5&#8217;9&#8243; Unleash The Fierce Title-Track Of Their Forthcoming &#8216;PRhyme&#8217; LP</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','zo','http://www.okayplayer.com/news/dj-premier-royce-da-59-adrian-younge-prhyme-mp3.html','<p> DJ Premier and Royce Da 5&#8217;9&#8243; have been teasing us with morsels from their upcoming collaborative project PRhyme for a minute now. Today they&#8217;ve unveiled a <a class="moretag" href="http://www.okayplayer.com/news/dj-premier-royce-da-59-adrian-younge-prhyme-mp3.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/dj-premier-royce-da-59-adrian-younge-prhyme-mp3.html">DJ Premier &#038; Royce Da 5&#8217;9&#8243; Unleash The Fierce Title-Track Of Their Forthcoming &#8216;PRhyme&#8217; LP</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 18:50:07.000000','2014-11-12 02:11:21.507525','2014-11-12 02:11:21.507525');
INSERT INTO "bars" VALUES(6,'Raekwon & Ghostface Rework Troy Ave’s “All About The Money”','<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/raekwon-ghostface-killah-all-about-the-money-remix-lead.jpg"><img src="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/raekwon-ghostface-killah-all-about-the-money-remix-lead.jpg" alt="Raekwon &amp; Ghostface Killah Join Forces To Rework A Troy Ave Track With The &quot;All About The Money&quot; (Remix)." width="600" height="600" class="alignnone size-full wp-image-81104" /></a></p>
<p><strong><a href="http://www.okayplayer.com/news/raekwon-tbt-we-wanna-thank-you-mixtape-stream.html">Raekwon</a></strong> and <strong><a href="http://www.okayplayer.com/news/ghostface-killah-love-dont-live-here-no-more-mp3-36-seasons-lp.html">Ghostface Killah</a></strong> join forces to rework a popular <strong><a href="https://twitter.com/troyave" target="_blank">Troy Ave</a></strong> track with the arrival of the <a href="https://soundcloud.com/iceh2orecords/raekwon-ghostfacek-killah-all-about-the-money-remix-dirty" target="_blank">&#8220;All About The Money&#8221; (Remix)</a>.  Trading bars over the spare trap production, the <strong><a href="http://www.okayplayer.com/news/the-wu-tang-clan-ruckus-in-b-minor-mp3.html">Wu-Tang</a></strong> representatives serve up a slang editorial dense with all of the hallmarks have come to expect.  Dropping nods to gold eagles and cuban links, Rae and Ghost toast to their respective reps as legendary MC&#8217;s.  Check the track below to listen to the &#8220;All About The Money&#8221; (Remix).  Pre-order Wu-Tang Clan&#8217;s <em><a href="https://itunes.apple.com/us/album/a-better-tomorrow/id934882788" target="_blank">A Better Tomorrow</a></em> LP via <a href="https://itunes.apple.com/us/album/a-better-tomorrow/id934882788" target="_blank">iTunes</a>.  Stay tuned for more from Raekwon and Ghostface Killah.  </p>
<p><iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/175805177&amp;color=ff4200&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/raekwon-ghostface-killah-all-about-the-money-remix-mp3.html">Raekwon &#038; Ghostface Rework Troy Ave&#8217;s &#8220;All About The Money&#8221;</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','karaslamb','http://www.okayplayer.com/news/raekwon-ghostface-killah-all-about-the-money-remix-mp3.html','<p>Raekwon and Ghostface Killah join forces to rework a popular Troy Ave track with the arrival of the &#8220;All About The Money&#8221; (Remix). Trading bars <a class="moretag" href="http://www.okayplayer.com/news/raekwon-ghostface-killah-all-about-the-money-remix-mp3.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/raekwon-ghostface-killah-all-about-the-money-remix-mp3.html">Raekwon &#038; Ghostface Rework Troy Ave&#8217;s &#8220;All About The Money&#8221;</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 18:08:54.000000','2014-11-12 02:11:21.534632','2014-11-12 02:11:21.534632');
INSERT INTO "bars" VALUES(7,'OKP Presents : Bilal & Dragons Of Zynth At Brooklyn Bowl w/ Rashad Smith On 12/11','<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/bilal-dragons-of-zynth-brooklyn-bowl-rashad-smith-12-11.jpg"><img class="alignnone size-full wp-image-81052" src="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/bilal-dragons-of-zynth-brooklyn-bowl-rashad-smith-12-11.jpg" alt="OKP Presents : Bilal &amp; Dragons Of Zynth At Brooklyn Bowl w/ Rashad Smith On 12/11" width="715" height="715" /></a></p>
<p>It&#8217;s that time of the year again, folks. Okayplayer is proud to announce that we&#8217;ll be taking over <a href="http://www.brooklynbowl.com/" target="_blank"><strong>Brooklyn Bowl</strong></a> for another proper holiday warm-up on December 11th with OKP&#8217;s favorite soul-searing musical madman <a href="http://www.okayplayer.com/tag/bilal%20"><strong>Bilal</strong></a>, Brooklyn&#8217;s own <a href="http://en.wikipedia.org/wiki/Dragons_of_Zynth" target="_blank"><strong>Dragons Of Zynth</strong></a> and best-kept-secret of the Golden Age legend <a href="http://www.discogs.com/artist/101845-Rashad-Smith?type=Credits&amp;subtype=Production" target="_blank"><strong>Rashad &#8220;Tumbling Dice&#8221; Smith</strong></a> bringing you heat on the ones and twos, produced by <strong><a href="http://www.jillnewmanproductions.com/" target="_blank">Jill Newman Productions</a></strong>. But the funk won&#8217;t stop there, as <a href="http://www.okayplayer.com/tag/questlove%20" target="_blank"><strong>Questlove</strong></a> will be taking the baton with another masterful Bowl Train set, the only proper way to tie off any Thursday night in Brooklyn. So come one, come all. Bring your father, your mother, your sister and your brother over to Brooklyn Bowl Thursday December 11th for an evening of funky frequencies and sonic seduction with Bilal, Rashad Smith, Dragons Of Zynth (&#8230;and maybe even a few special guests if we&#8217;re lucky) then have a nightcap with DJ Questo, king of the throwback. Hit the links below to grab your tickets and so promptly. This one&#8217;s a sure-shot sell-out.</p>
<p>&nbsp;</p>
<p><a href="https://www.ticketfly.com/purchase/event/708037?__utma=1.429606474.1415677294.1415677294.1415677294.1&amp;__utmb=1.2.10.1415677294&amp;__utmc=1&amp;__utmx=-&amp;__utmz=1.1415677294.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)&amp;__utmv=-&amp;__utmk=246647684" target="_blank"><strong>&gt;&gt;&gt;Purchase Tickets To Bilal, Dragon Of Zynth &amp; Rashad &#8220;Tumbling Dice&#8221; Smith (via Brooklyn Bowl) </strong></a></p>
<p><a href="http://www.ticketfly.com/purchase/event/712547?__utma=1.2038520777.1413289531.1414173280.1415735032.5&amp;__utmb=1.1.10.1415735032&amp;__utmc=1&amp;__utmx=-&amp;__utmz=1.1415735032.5.4.utmcsr=google%7Cutmccn=(organic)%7Cutmcmd=organic%7Cutmctr=(not%20provided)&amp;__utmv=-&amp;__utmk=245737732"><strong>&gt;&gt;&gt;Purchase Tickets To Bowl Train w/ DJ Questlove</strong></a></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/bilal-dragons-of-zynth-brooklyn-bowl-live-music.html">OKP Presents : Bilal &#038; Dragons Of Zynth At Brooklyn Bowl w/ Rashad Smith On 12/11</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','zo','http://www.okayplayer.com/news/bilal-dragons-of-zynth-brooklyn-bowl-live-music.html','<p>It&#8217;s that time of the year again, folks. Okayplayer is proud to announce that we&#8217;ll be taking over Brooklyn Bowl for another proper holiday warm-up <a class="moretag" href="http://www.okayplayer.com/news/bilal-dragons-of-zynth-brooklyn-bowl-live-music.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/bilal-dragons-of-zynth-brooklyn-bowl-live-music.html">OKP Presents : Bilal &#038; Dragons Of Zynth At Brooklyn Bowl w/ Rashad Smith On 12/11</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 18:00:28.000000','2014-11-12 02:11:21.566776','2014-11-12 02:11:21.566776');
INSERT INTO "bars" VALUES(8,'The Sugarhill Gang’s Big Bank Hank Dies At 57','<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/sugarhill-gang-big-bank-hank-dead-at-57-lead.jpg"><img src="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/sugarhill-gang-big-bank-hank-dead-at-57-lead.jpg" alt="Rapper &amp; Founder Of The Sugarhill Gang, Big Bank Hank Has Died At The Age Of 57 Following A Battle With Cancer, According To Reports From TMZ." width="700" height="394" class="alignnone size-full wp-image-81100" /></a></p>
<p>Rapper and co-founder of the groundbreaking hip-hop group <strong><a href="http://en.wikipedia.org/wiki/The_Sugarhill_Gang" target="_blank">The Sugarhill Gang</a></strong>, <strong><a href="http://en.wikipedia.org/wiki/Big_Bank_Hank" target="_blank">Big Bank Hank</a></strong> has died of cancer at 57 according to reports from <a href="http://www.tmz.com/2014/11/11/sugarhill-gang-big-bank-hank-dies-cancer-dead-rappers-delight/" target="_blank">TMZ</a>.  The news comes weeks after the 35th anniversary of the group&#8217;s 1979 classic <a href="https://www.youtube.com/watch?v=rKTUAESacQM" target="_blank">&#8220;Rapper&#8217;s Delight&#8221;</a> first emerging on the <a href="http://www.billboard.com/articles/news/6281561/sugarhill-gang-rappers-delight-first-chart-appearance-anniversary" target="_blank">Billboard</a> chart.  The crew formed in Englewood, New Jersey and reached that milestone just two years after their founding in 1977.  Considered one of the godfathers of rap, Hank&#8217;s contributions as a member of the Sugarhill Gang marked the first signs of hip-hop&#8217;s commercial viability.  The mainstream success of the trio&#8217;s seminal single would ultimately help to usher in major opportunities for subsequent generations of MC&#8217;s to realize massive wealth and success in a genre that was once dismissed as &#8220;noise&#8221; and largely predicted to crash and burn.  In conversation with <a href="http://www.foxnews.com/entertainment/2014/11/11/sugarhill-gang-founder-big-bank-hank-dies/" target="_blank">FOX News</a>, the group&#8217;s manager <strong>David Mallie</strong> noted that Jackson died early this morning from kidney complications due to cancer.  Hank is survived by his Sugarhill Gang brothers <strong><a href="http://en.wikipedia.org/wiki/Wonder_Mike" target="_blank">Wonder Mike</a></strong> and <strong><a href="http://en.wikipedia.org/wiki/The_Sugarhill_Gang" target="_blank">Master Gee</a></strong> and mourned by lovers of hip-hop culture across the world.  RIP Big Bank Hank.</p>
<p><iframe width="715" height="402" src="http://www.okayplayer.com//www.youtube.com/embed/cELt9nCWY_0?rel=0" frameborder="0" allowfullscreen></iframe></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/the-sugarhill-gang-big-bank-hank-dead-at-57.html">The Sugarhill Gang&#8217;s Big Bank Hank Dies At 57</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','karaslamb','http://www.okayplayer.com/news/the-sugarhill-gang-big-bank-hank-dead-at-57.html','<p>Rapper and co-founder of the groundbreaking hip-hop group The Sugarhill Gang, Big Bank Hank has died of cancer at 57 according to reports from TMZ. <a class="moretag" href="http://www.okayplayer.com/news/the-sugarhill-gang-big-bank-hank-dead-at-57.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/the-sugarhill-gang-big-bank-hank-dead-at-57.html">The Sugarhill Gang&#8217;s Big Bank Hank Dies At 57</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 17:42:28.000000','2014-11-12 02:11:21.604941','2014-11-12 02:11:21.604941');
INSERT INTO "bars" VALUES(9,'Ghostface Killah Drops “Love Don’t Live Here No More” + Announces New Concept LP ‘ 36 Seasons’','<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/ghostface-killah-love-dont-live-here-no-more-mp3-36-seasons-lp-main.jpg"><img class="alignnone size-full wp-image-81099" src="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/ghostface-killah-love-dont-live-here-no-more-mp3-36-seasons-lp-main.jpg" alt="http://pitchfork.com/news/57400-ghostface-killah-announces-new-album-36-seasons-shares-love-dont-live-here-no-more/" width="715" height="1060" /></a></p>
<p>Take heed, Wu disciples. <a href="http://www.okayplayer.com/tag/ghostface-killah"><strong>Ghostface Killah</strong></a> just dropped a bomb on the world, announcing yet another GFK project will arrive this year in the form of the concept piece <em>36 Seasons</em>. In it Ghostface will take the form of a sonic superhero &#8220;inspired by a quest for personal retribution and bent on saving his community from the grips of crooked authority and urban decay.&#8221; And who better to do so than the mighty Tony Starks; Iron Man in the flesh. The first offering from the album comes in the form of the soulful number &#8220;Love Don&#8217;t Live Here No More,&#8221; featuring the soaring vocal stylings of Blue Note Records&#8217; r&amp;bstress <strong><a href="http://www.okayplayer.com/tag/kandace-springs">Kandace Springs</a> </strong>on the hook. The album will be hitting stores December 9th complete with 20-page booklet of illustrations by various comic artists, just a week after the entirety of <a href="http://www.okayplayer.com/tag/wu-tang-clan"><strong>The Wu-Tang Clan</strong></a> comes storming back on the release of their <em>A Better Tomorrow </em>LP, which will prominently feature ole cocaine biceps. But that isn&#8217;t all the Shaolin mic-slayer&#8217;s got on the way, as he&#8217;ll be dropping the collaborative LP <em>Sour Soul</em> with Canadian punk-funkateers <strong><a href="http://www.okayplayer.com/tag/badbadnotgood">BADBADNOTGOOD</a> </strong>on February 17th. So there&#8217;s a whole lot of loving heading our way. You ready? Stream the lead-off single &#8220;Love Don&#8217;t Live Here No More&#8221; down below and preorder <em>36 Seasons</em> on <a href="http://bit.ly/10RhPW5" target="_blank">iTunes</a> today.</p>
<p><iframe src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/176385040&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false" width="100%" height="166" frameborder="no" scrolling="no"></iframe></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/ghostface-killah-love-dont-live-here-no-more-mp3-36-seasons-lp.html">Ghostface Killah Drops &#8220;Love Don&#8217;t Live Here No More&#8221; + Announces New Concept LP &#8216; 36 Seasons&#8217;</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','zo','http://www.okayplayer.com/news/ghostface-killah-love-dont-live-here-no-more-mp3-36-seasons-lp.html','<p>Take heed, Wu disciples. Ghostface Killah just dropped a bomb on the world, announcing yet another GFK project will arrive this year in the form <a class="moretag" href="http://www.okayplayer.com/news/ghostface-killah-love-dont-live-here-no-more-mp3-36-seasons-lp.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/ghostface-killah-love-dont-live-here-no-more-mp3-36-seasons-lp.html">Ghostface Killah Drops &#8220;Love Don&#8217;t Live Here No More&#8221; + Announces New Concept LP &#8216; 36 Seasons&#8217;</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 17:04:32.000000','2014-11-12 02:11:21.638198','2014-11-12 02:11:21.638198');
INSERT INTO "bars" VALUES(10,'SmCity – “Cinematic Moment” (prod. by !llmind)','<p><a href="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/smcity-illmind-cinematic-moment-mp3.jpg"><img class="alignnone size-full wp-image-81030" src="http://okp-cdn.okayplayer.com/wp-content/uploads/2014/11/smcity-illmind-cinematic-moment-mp3.jpg" alt="SmCity - &quot;Cinematic Moment&quot; (prod. by !llmind)" width="715" height="715" /></a></p>
<p><a href="https://soundcloud.com/smcitymusic" target="_blank"><strong>SmCity</strong></a> goes off on the <a href="http://www.okayplayer.com/tag/illmind"><strong>!llmind</strong></a>-crafted loosie &#8220;Cinematic Moment&#8221; from his forthcoming mixtape<em> Empire Falls</em>. The studious and dynamic beat constructor forges a bed of boom-bap-tinged sonics for the Capital City wordsmith to to get loose on. You may remember the Sm from past collaborations with <a href="http://www.okayplayer.com/tag/oddisee"><strong>Oddisee</strong></a>, <a href="http://www.okayplayer.com/tag/the-kid-daytona"><strong>The Kid Daytona</strong></a>, <a href="http://www.okayplayer.com/tag/skyzoo"><strong>Skyzoo</strong></a> and more, but your boy&#8217;s been cooking up a new batch for the heads and we&#8217;re poised to say it&#8217;s shaping up to be a formidable one. <em>Empire Falls </em>is due out on December 3rd with extensive production from !llmind and guest appearances from <strong><a href="http://www.okayplayer.com/tag/maimouna-youssef">Maimouna Youssef</a>, <a href="http://www.okayplayer.com/tag/bj-the-chicago-kid">BJ The Chicago Kid</a></strong> and <a href="https://www.facebook.com/EmannyMusic" target="_blank"><strong>Emanny</strong></a>. Listen to SmCity&#8217;s latest drop &#8220;Cinematic Moment&#8221; below and preorder <em>Empire Falls </em>on <a href="http://bit.ly/1uWbfLt" target="_blank">iTunes</a> today.</p>
<p><iframe src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/176129234&amp;color=b59349&amp;show_artwork=false" width="100%" height="166" frameborder="no" scrolling="no"></iframe></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/smcity-illmind-cinematic-moment-mp3.html">SmCity &#8211; &#8220;Cinematic Moment&#8221; (prod. by !llmind)</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','zo','http://www.okayplayer.com/news/smcity-illmind-cinematic-moment-mp3.html','<p>SmCity goes off on the !llmind-crafted loosie &#8220;Cinematic Moment&#8221; from his forthcoming mixtape Empire Falls. The studious and dynamic beat constructor forges a bed of <a class="moretag" href="http://www.okayplayer.com/news/smcity-illmind-cinematic-moment-mp3.html">keep reading &#187;</a></p>
<p>The post <a rel="nofollow" href="http://www.okayplayer.com/news/smcity-illmind-cinematic-moment-mp3.html">SmCity &#8211; &#8220;Cinematic Moment&#8221; (prod. by !llmind)</a> appeared first on <a rel="nofollow" href="http://www.okayplayer.com">Okayplayer</a>.</p>
','2014-11-11 17:00:17.000000','2014-11-12 02:11:21.675355','2014-11-12 02:11:21.675355');
CREATE TABLE "hiphop_sites" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar(255), "image_url" varchar(255), "description" varchar(255), "created_at" datetime, "updated_at" datetime);
INSERT INTO "hiphop_sites" VALUES(1,'http://google.com',NULL,NULL,'2014-11-12 03:48:30.112652','2014-11-12 03:48:30.112652');
INSERT INTO "hiphop_sites" VALUES(2,'http://google.com','','searchy','2014-11-12 03:55:10.872209','2014-11-12 03:55:10.872209');
INSERT INTO "hiphop_sites" VALUES(3,'http://allhiphop.com','http://1.gravatar.com/blavatar/7c1a6eca68631802f684e0798871ec7a?','allhiphop','2014-11-12 04:08:18.787430','2014-11-12 04:08:18.787430');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('bars',10);
INSERT INTO "sqlite_sequence" VALUES('hiphop_sites',3);
CREATE UNIQUE INDEX "unique_schema_migrations" ON "schema_migrations" ("version");
COMMIT;
